"""added catalog_no to salesorder

Revision ID: 022983fb9069
Revises: c1891c150411
Create Date: 2017-12-14 17:03:25.470754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022983fb9069'
down_revision = 'c1891c150411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('catalog_no', sa.Integer(), nullable=True))
    op.drop_constraint('sales_orders_record_id_fkey', 'sales_orders', type_='foreignkey')
    op.create_foreign_key(None, 'sales_orders', 'records', ['catalog_no'], ['catalog_no'])
    op.drop_column('sales_orders', 'record_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.create_foreign_key('sales_orders_record_id_fkey', 'sales_orders', 'records', ['record_id'], ['id'])
    op.drop_column('sales_orders', 'catalog_no')
    # ### end Alembic commands ###
