"""added userID to salesorder

Revision ID: c1891c150411
Revises: 
Create Date: 2017-12-13 13:14:32.075525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1891c150411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'user_id')
    # ### end Alembic commands ###
